receivers:
  otlp:
    protocols:
      grpc:
exporters:
  otlp/jaeger:
    endpoint: jaeger-service:4317
    tls:
      insecure: true
  logging:
    loglevel: info
processors:
  batch:
    send_batch_size: 1
  resource:
    attributes:
      - key: tas.org
        value: Team
        action: insert
      - key: deployment.environment
        value: dev
        action: insert
service:
  pipelines:
    traces:
      receivers: [ otlp ]
      processors: [ resource,batch ]
      exporters: [ otlp/jaeger,logging ]
    metrics:
      receivers: [ otlp ]
      processors: [ resource,batch ]
      exporters: [ logging ]
